package geektime.spring.springbucks.mapper;

import geektime.spring.springbucks.pojo.OrderCoffee;
import geektime.spring.springbucks.pojo.OrderCoffeeExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface OrderCoffeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Jun 05 16:50:20 CST 2022
     */
    long countByExample(OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Jun 05 16:50:20 CST 2022
     */
    int deleteByExample(OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Jun 05 16:50:20 CST 2022
     */
    @Insert({
        "insert into T_ORDER_COFFEE (COFFEE_ORDER_ID, ITEMS_ID)",
        "values (#{coffeeOrderId,jdbcType=BIGINT}, #{itemsId,jdbcType=BIGINT})"
    })
    int insert(OrderCoffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Jun 05 16:50:20 CST 2022
     */
    int insertSelective(OrderCoffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Jun 05 16:50:20 CST 2022
     */
    List<OrderCoffee> selectByExampleWithRowbounds(OrderCoffeeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Jun 05 16:50:20 CST 2022
     */
    List<OrderCoffee> selectByExample(OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Jun 05 16:50:20 CST 2022
     */
    int updateByExampleSelective(@Param("record") OrderCoffee record, @Param("example") OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Jun 05 16:50:20 CST 2022
     */
    int updateByExample(@Param("record") OrderCoffee record, @Param("example") OrderCoffeeExample example);
}